Tests for Choleski's algorithm

In [ ]:
import numpy as np 
action_space = 5


In [1]:
import numpy as np
action_space = 5
dim = (5*(5+1))//2
print(dim)

15


In [4]:
cholesky_diag_index = np.arange(action_space) + 1


In [5]:
cholesky_diag_index

array([1, 2, 3, 4, 5])

In [6]:
cholesky_diag_index = (cholesky_diag_index * (cholesky_diag_index + 1)) // 2 - 1

In [7]:
cholesky_diag_index

array([ 0,  2,  5,  9, 14], dtype=int32)

In [13]:
tril_indices = np.tril_indices(5)

In [14]:
tril_ind

(array([0, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4], dtype=int64),
 array([0, 0, 1, 0, 1, 2, 0, 1, 2, 3, 0, 1, 2, 3, 4], dtype=int64))

In [27]:
cholesky = np.zeros((5, 5))

In [28]:
cholesky

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
cholesky[tril_indices[0], tril_indices[1]] = cholesky_vector

In [22]:
cholesky

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 2.,  3.,  0.,  0.,  0.],
       [ 4.,  5.,  6.,  0.,  0.],
       [ 7.,  8.,  9., 10.,  0.],
       [11., 12., 13., 14., 15.]])

In [18]:
dim

15

In [23]:
cholesky_vector = np.arange(dim)+1

In [24]:
cholesky_vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [26]:
cholesky_vector[cholesky_diag_index] = -1

In [29]:
cholesky[tril_indices[0], tril_indices[1]] = cholesky_vector

In [30]:
cholesky

array([[-1.,  0.,  0.,  0.,  0.],
       [ 2., -1.,  0.,  0.,  0.],
       [ 4.,  5., -1.,  0.,  0.],
       [ 7.,  8.,  9., -1.,  0.],
       [11., 12., 13., 14., -1.]])

In [24]:
import numpy as np
x = np.arange(5)

In [25]:
x

array([0, 1, 2, 3, 4])

In [26]:
x = np.expand_dims(x,-1)

In [27]:
a =x
b = x

In [28]:
c = zip(a,b,x)

In [29]:
c 

In [30]:
for i,j,k in c:
    print('{},{},{}'.format(i,j,k))

[0],[0],[0]
[1],[1],[1]
[2],[2],[2]
[3],[3],[3]
[4],[4],[4]


In [42]:
d = x

In [43]:
d

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [52]:
e = d +1
f = e + 1

In [54]:
for i,j,k in zip(d,e,f):
    print('{},{},{}'.format(i,j,k))

[0],[1],[2]
[1],[2],[3]
[2],[3],[4]
[3],[4],[5]
[4],[5],[6]


In [48]:
f 

array([[3, 4, 5, 6, 7]])

In [49]:
e 

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [50]:
f 

array([[3, 4, 5, 6, 7]])

In [51]:
d 

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [55]:
from unityagents import UnityEnvironment
env = UnityEnvironment(file_name='../../deep-reinforcement-learning/p2_continuous-control/Crawler_Windows_x86_64/Crawler.exe')

INFO:unityagents:
'Academy' started successfully!
Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		
Unity brain name: CrawlerBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 129
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): 20
        Vector Action descriptions: , , , , , , , , , , , , , , , , , , , 


In [56]:
print(env)

Unity Academy name: Academy
        Number of Brains: 1
        Number of External Brains : 1
        Lesson number : 0
        Reset Parameters :
		
Unity brain name: CrawlerBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 129
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): 20
        Vector Action descriptions: , , , , , , , , , , , , , , , , , , , 


In [57]:
print(env.brains)

{'CrawlerBrain': <unityagents.brain.BrainParameters object at 0x0000013FA5A57D30>}


In [69]:
print(env.brains['CrawlerBrain'])

Unity brain name: CrawlerBrain
        Number of Visual Observations (per agent): 0
        Vector Observation space type: continuous
        Vector Observation space size (per agent): 129
        Number of stacked Vector Observation: 1
        Vector Action space type: continuous
        Vector Action space size (per agent): 20
        Vector Action descriptions: , , , , , , , , , , , , , , , , , , , 


In [99]:
brain = env.brains[env.brain_names[0]]

In [100]:
brain 

In [101]:
brain.vector_observation_space_size

129

In [78]:
x.num_stacked_vector_observations

1

In [79]:
x.vector_action_space_size

20

In [80]:
x.reset()

AttributeError: 'BrainParameters' object has no attribute 'reset'

In [81]:
env.reset()

{'CrawlerBrain': <unityagents.brain.BrainInfo at 0x13fa5a7d208>}

In [88]:
env_info = env.reset()

In [91]:
env_info['CrawlerBrain'].vector_action_space_size

AttributeError: 'BrainInfo' object has no attribute 'vector_action_space_size'

In [102]:
env.close()